version: "3.5"

networks:
  mysql: ~
  mongodb: ~
  nginx: ~
  grafana: ~
  nextcloud: ~
  prometheus-grafana: ~
  prometheus-node-exporter: ~

  i-mutabakat:
    external:
      name: i-mutabakat
  kitapdostu:
    external:
      name: kitapdostu

services:
  mysql: 
    image: mariadb
    container_name: mysql
    networks: 
      - mysql
    env_file:
      - env/mysql.env
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/mysql:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    env_file:
      - env/mongodb.env
    networks:
      - mongodb
    restart: unless-stopped
    ports:
      - "27018:27017/tcp"
    volumes:
      - "/opt/volumes/mongodb:/data/db"
      - "/opt/backup/mongodb:/backup"
      - "/etc/localtime:/etc/localtime:ro"

  grafana: 
    depends_on: 
      - prometheus
      - node-exporter
    env_file:
      - env/grafana.env 
    image: "grafana/grafana:latest"
    container_name: grafana
    networks: 
      - grafana
      - prometheus-grafana
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/grafana:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"

  nginx: 
    depends_on: 
      - nextcloud
      - grafana
    image: "nginx:alpine"
    container_name: nginx
    external_links:
      - i-mutabakat
      - kitapdostu
    networks: 
      - nginx
      - nextcloud
      - grafana
      - i-mutabakat
      - kitapdostu
    ports: 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/opt/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "/opt/volumes/nginx/ssl:/etc/nginx/ssl:ro"
      - "/opt/volumes/nginx/static:/etc/nginx/static:ro"
      - "/opt/volumes/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/opt/volumes/nginx/cache:/etc/nginx/cache:rw"
      - "/etc/localtime:/etc/localtime:ro"

  nextcloud: 
    depends_on: 
      - mysql
    image: "nextcloud"
    container_name: nextcloud
    networks: 
      - nextcloud
      - mysql
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/nextcloud:/var/www/html"
      - "/etc/localtime:/etc/localtime:ro"

  node-exporter: 
    image: prom/node-exporter
    container_name: node-exporter
    networks: 
      - prometheus-node-exporter

  prometheus: 
    depends_on: 
      - node-exporter
    image: "prom/prometheus:latest"
    container_name: prometheus
    networks: 
      - prometheus-grafana
      - prometheus-node-exporter
    restart: unless-stopped
    volumes: 
      - "/opt/docker-files/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/opt/volumes/prometheus:/var/prometheus/data"
      - "/etc/localtime:/etc/localtime:ro"
