version: "3.4"

networks:
  mysql: ~
  mongodb: ~
  nginx: ~
  grafana: ~
  nextcloud: ~
  prometheus-grafana: ~
  prometheus-node-exporter: ~

  ## Web
  i-mutabakat: ~
  kitapdostu: ~

volumes: 
  mysql: ~
  mongodb: ~
  nginx: ~
  grafana: ~
  nextcloud: ~
  prometheus: ~

services:
  i-mutabakat:
    build: "${PROJECT_DIR}/i-mutabakat"
    depends_on:
      - mongodb
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/var/www/html/i-mutabakat:/home"
    links:
      - mongodb
    env_file:
      - env/i-mutabakat.env
    networks:
      - i-mutabakat
      - mongodb
    restart: unless-stopped

  kitapdostu:
    build: "${PROJECT_DIR}/kitapdostu"
    depends_on:
      - mongodb
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/var/www/html/kitapdostu:/home"
    links:
      - mongodb
    env_file:
      - env/kitapdostu.env
    networks:
      - kitapdostu
      - mongodb
    restart: unless-stopped

  mysql: 
    image: mariadb
    container_name: mysql
    networks: 
      - mysql
    env_file:
      - env/mysql.env
    restart: unless-stopped
    volumes: 
      - "mysql:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    env_file:
      - env/mongodb.env
    networks:
      - mongodb
    restart: unless-stopped
    ports:
      - "27018:27017/tcp"
    volumes:
      - "mongodb:/data/db"
      - "${MONGODB_BACKUP_DIR}:/backups"

  grafana: 
    depends_on: 
      - prometheus
      - node-exporter
    env_file:
      - env/grafana.env 
    image: "grafana/grafana:latest"
    container_name: grafana
    networks: 
      - grafana
      - prometheus-grafana
    restart: unless-stopped
    volumes: 
      - "grafana:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"

  nginx: 
    depends_on: 
      - nextcloud
      - grafana
    image: "nginx:alpine"
    container_name: nginx
    networks: 
      - nginx
      - nextcloud
      - grafana
      - i-mutabakat
      - kitapdostu
    ports: 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes: 
      - "nginx:/etc/nginx"
      - "${NGINX_HOST_DIR}/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "${NGINX_HOST_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${NGINX_HOST_DIR}/ssl:/etc/nginx/ssl:ro"
      - "${NGINX_HOST_DIR}/static:/etc/nginx/static:ro"
      - "${NGINX_HOST_DIR}/conf.d:/etc/nginx/conf.d:ro"
      - "${NGINX_HOST_DIR}/cache:/etc/nginx/cache:rw"
      - "/etc/localtime:/etc/localtime:ro"

  nextcloud: 
    depends_on: 
      - mysql
    image: "nextcloud"
    container_name: nextcloud
    networks: 
      - nextcloud
      - mysql
    restart: unless-stopped
    volumes: 
      - "nextcloud:/var/www/html"
      - "/etc/localtime:/etc/localtime:ro"

  node-exporter: 
    image: prom/node-exporter
    container_name: node-exporter
    networks: 
      - prometheus-node-exporter

  prometheus: 
    depends_on: 
      - node-exporter
    image: "prom/prometheus:latest"
    container_name: prometheus
    networks: 
      - prometheus-grafana
      - prometheus-node-exporter
    restart: unless-stopped
    volumes: 
      - "${DOCKER_FILES_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"
      - "/etc/localtime:/etc/localtime:ro"
