version: "3.5"

networks:
  mysql: ~
  mongodb: ~
  phpmyadmin: ~
  rabbitmq: ~
  nginx: ~
  pritunl: ~
  grafana: ~
  nextcloud: ~
  prometheus-grafana: ~
  prometheus-node-exporter: ~

  postal:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 73.0.0.0/16

  i-mutabakat:
    external:
      name: i-mutabakat
  moonlight-land:
    external:
      name: moonlight-land
  moonlight-web:
    external:
      name: moonlight-web
  olimpus-wordpress:
    external:
      name: olimpus-wordpress

services:
  mysql: 
    image: mariadb
    container_name: mysql
    networks: 
      - mysql
    env_file: env/mysql.env
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/mysql:/var/lib/mysql"
      - "/opt/backup/mysql:/backup"
      - "/etc/localtime:/etc/localtime:ro"

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    env_file: env/mongodb.env
    networks:
      - mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - "/opt/volumes/mongodb:/data/db"
      - "/opt/backup/mongodb:/backup"
      - "/etc/localtime:/etc/localtime:ro"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: env/phpmyadmin.env 
    networks:
      - mysql
      - phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - "/opt/volumes/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
      - "/opt/volumes/phpmyadmin/sessions:/sessions"
      - "/etc/localtime:/etc/localtime:ro"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    env_file: env/rabbitmq.env 
    networks:
      - rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    privileged: true
    restart: unless-stopped
    volumes:
      - "/opt/volumes/rabbitmq:/var/lib/rabbitmq"
      - "/etc/localtime:/etc/localtime:ro"

  postal:
    depends_on:
      - mysql
      - rabbitmq
    image: alinuxninja/postal
    container_name: postal
    command: run
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    networks:
      mysql:
      rabbitmq:
      postal:
        ipv4_address: 73.0.0.10
    ports:
      - "25:25"
      - "5000:5000"
      - "5010:5010"
      - "5011:5011"
    privileged: true
    restart: unless-stopped
    volumes:
      - "/opt/docker-files/postal.yml:/opt/postal/config/postal.yml:ro"
      - "/opt/volumes/postal/config:/opt/postal/config"
      - "/opt/volumes/postal/assets:/opt/postal/public/assets"
      - "/etc/localtime:/etc/localtime:ro"

  grafana: 
    depends_on: 
      - prometheus
      - node-exporter
    image: "grafana/grafana:latest"
    container_name: grafana
    env_file: env/grafana.env 
    networks: 
      - grafana
      - prometheus-grafana
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/grafana:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"

  nginx: 
    depends_on: 
      - nextcloud
      - grafana
      - rabbitmq
      - postal
      - pritunl
      - phpmyadmin
    image: "nginx:alpine"
    container_name: nginx
    external_links:
      - i-mutabakat
      - moonlight-land
      - moonlight-web
      - olimpus-wordpress
    networks: 
      - nginx
      - nextcloud
      - grafana
      - rabbitmq
      - postal
      - pritunl
      - phpmyadmin
      - i-mutabakat
      - moonlight-land
      - moonlight-web
      - olimpus-wordpress
    ports: 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/opt/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "/opt/volumes/nginx/ssl:/etc/nginx/ssl:ro"
      - "/opt/volumes/nginx/static:/etc/nginx/static:ro"
      - "/opt/volumes/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/opt/volumes/nginx/cache:/etc/nginx/cache:rw"
      - "/etc/localtime:/etc/localtime:ro"

  pritunl:
    depends_on:
      - mongodb
    env_file: env/pritunl.env
    image: "jippi/pritunl"
    container_name: pritunl
    networks:
      - pritunl
      - mongodb
    ports:
      - "1194:1194/udp"
    privileged: true
    command: >
      pritunl set app.reverse_proxy true
      && pritunl set app.server_ssl false
      && pritunl set app.server_port 9700
    restart: unless-stopped
    volumes:
      - "/opt/docker-files/pritunl.conf:/etc/pritunl.conf"
      - "/opt/volumes/pritunl:/var/lib/pritunl"
      - "/etc/localtime:/etc/localtime:ro"

  nextcloud: 
    depends_on: 
      - mysql
    image: "nextcloud"
    container_name: nextcloud
    networks: 
      - nextcloud
      - mysql
    restart: unless-stopped
    volumes: 
      - "/opt/volumes/nextcloud:/var/www/html"
      - "/etc/localtime:/etc/localtime:ro"

  node-exporter: 
    image: prom/node-exporter
    container_name: node-exporter
    networks: 
      - prometheus-node-exporter

  prometheus: 
    depends_on: 
      - node-exporter
    image: "prom/prometheus:latest"
    container_name: prometheus
    networks: 
      - prometheus-grafana
      - prometheus-node-exporter
    restart: unless-stopped
    volumes: 
      - "/opt/docker-files/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/opt/volumes/prometheus:/var/prometheus/data"
      - "/etc/localtime:/etc/localtime:ro"
