version: "3.5"

networks:
  i-mutabakat:
    name: i-mutabakat
  moonlight-land:
    name: moonlight-land
  olimpus-wordpress:
    name: olimpus-wordpress
  isletmem-api:
    name: isletmem-api

services:
  i-mutabakat:
    build: "/opt/projects/i-mutabakat"
    container_name: i-mutabakat
    depends_on:
      - mongodb
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/opt/projects/i-mutabakat/dist:/home"
      - "/opt/projects/i-mutabakat/node_modules:/home/node_modules:ro"
    links:
      - mongodb
    env_file:
      - /opt/docker/env/i-mutabakat.env
    networks:
      - mongodb
      - i-mutabakat
    restart: unless-stopped

  isletmem-api:
    container_name: isletmem-api
    image: strapi/strapi
    depends_on:
      - isletmem-db
    ports:
      - 1337:1337
    env_file:
      - /opt/docker/env/isletmem-api.env
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/opt/projects/isletmem-api:/srv/app"
    links:
      - isletmem-db
    networks:
      - isletmem-db
      - isletmem-api
    restart: unless-stopped
    command: "NODE_ENV=production npm start"

  moonlight-land:
    build: "/opt/projects/moonlight-land"
    container_name: moonlight-land
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/opt/projects/moonlight-land/dist:/home"
      - "/opt/projects/moonlight-land/node_modules:/home/node_modules:ro"
    env_file:
      - /opt/docker/env/moonlight-land.env
    networks:
      - moonlight-land
    restart: unless-stopped

  moonlight-web:
    build: "/opt/projects/moonlight-web"
    container_name: moonlight-web
    depends_on:
      - mongodb
    volumes:
      - "/usr/lib:/usr/lib:ro"
      - "/opt/projects/moonlight-web/dist:/home"
      - "/opt/projects/moonlight-web/node_modules:/home/node_modules:ro"
    links:
      - mongodb
    env_file:
      - /opt/docker/env/moonlight-web.env
    networks:
      - mongodb
      - moonlight-web
    restart: unless-stopped

  olimpus-wordpress:
    image: wordpress:latest
    container_name: olimpus-wordpress
    depends_on:
      - mysql
    volumes:
      - "/opt/wordpress/olimpus.com.tr/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "/opt/wordpress/olimpus.com.tr/wp-app:/var/www/html"
    links:
      - mysql
    env_file:
      - /opt/docker/env/olimpus-wordpress.env
    networks:
      - mysql
      - olimpus-wordpress
    restart: unless-stopped
